name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Test
        run: yarn test

      - name: Build project
        run: yarn build
        env:
          PUBLIC_NOTION_SECRET: ${{ secrets.PUBLIC_NOTION_SECRET }}
          PUBLIC_DATABASE_ID: ${{ secrets.PUBLIC_DATABASE_ID }}

      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
